// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/telemetry.proto

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_INSIDE   State = 0
	State_WARNING  State = 1
	State_BREACHED State = 2
	State_MOVING   State = 3
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "INSIDE",
		1: "WARNING",
		2: "BREACHED",
		3: "MOVING",
	}
	State_value = map[string]int32{
		"INSIDE":   0,
		"WARNING":  1,
		"BREACHED": 2,
		"MOVING":   3,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_telemetry_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_proto_telemetry_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{0}
}

type Cue int32

const (
	Cue_CUE_NONE  Cue = 0
	Cue_AUDIO     Cue = 1
	Cue_VIBRATION Cue = 2
	Cue_PULSE     Cue = 3
)

// Enum value maps for Cue.
var (
	Cue_name = map[int32]string{
		0: "CUE_NONE",
		1: "AUDIO",
		2: "VIBRATION",
		3: "PULSE",
	}
	Cue_value = map[string]int32{
		"CUE_NONE":  0,
		"AUDIO":     1,
		"VIBRATION": 2,
		"PULSE":     3,
	}
)

func (x Cue) Enum() *Cue {
	p := new(Cue)
	*p = x
	return p
}

func (x Cue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cue) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_telemetry_proto_enumTypes[1].Descriptor()
}

func (Cue) Type() protoreflect.EnumType {
	return &file_proto_telemetry_proto_enumTypes[1]
}

func (x Cue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cue.Descriptor instead.
func (Cue) EnumDescriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{1}
}

type Side int32

const (
	Side_SIDE_NONE Side = 0
	Side_LEFT      Side = 1
	Side_RIGHT     Side = 2
	Side_BOTH      Side = 3
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_NONE",
		1: "LEFT",
		2: "RIGHT",
		3: "BOTH",
	}
	Side_value = map[string]int32{
		"SIDE_NONE": 0,
		"LEFT":      1,
		"RIGHT":     2,
		"BOTH":      3,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_telemetry_proto_enumTypes[2].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_proto_telemetry_proto_enumTypes[2]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{2}
}

type FarmSecond struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FarmerId      string                 `protobuf:"bytes,1,opt,name=farmer_id,json=farmerId,proto3" json:"farmer_id,omitempty"`
	TimeMs        int64                  `protobuf:"varint,2,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	Cows          []*Cow                 `protobuf:"bytes,3,rep,name=cows,proto3" json:"cows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarmSecond) Reset() {
	*x = FarmSecond{}
	mi := &file_proto_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarmSecond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmSecond) ProtoMessage() {}

func (x *FarmSecond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmSecond.ProtoReflect.Descriptor instead.
func (*FarmSecond) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *FarmSecond) GetFarmerId() string {
	if x != nil {
		return x.FarmerId
	}
	return ""
}

func (x *FarmSecond) GetTimeMs() int64 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

func (x *FarmSecond) GetCows() []*Cow {
	if x != nil {
		return x.Cows
	}
	return nil
}

type Cow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollarId      string                 `protobuf:"bytes,1,opt,name=collar_id,json=collarId,proto3" json:"collar_id,omitempty"`
	PaddockId     string                 `protobuf:"bytes,2,opt,name=paddock_id,json=paddockId,proto3" json:"paddock_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	LatE6         int32                  `protobuf:"zigzag32,4,opt,name=lat_e6,json=latE6,proto3" json:"lat_e6,omitempty"`
	LngE6         int32                  `protobuf:"zigzag32,5,opt,name=lng_e6,json=lngE6,proto3" json:"lng_e6,omitempty"`
	HeadingDeg    uint32                 `protobuf:"varint,6,opt,name=heading_deg,json=headingDeg,proto3" json:"heading_deg,omitempty"`
	State         State                  `protobuf:"varint,7,opt,name=state,proto3,enum=telemetry.State" json:"state,omitempty"`
	Level         Cue                    `protobuf:"varint,8,opt,name=level,proto3,enum=telemetry.Cue" json:"level,omitempty"`
	Side          Side                   `protobuf:"varint,9,opt,name=side,proto3,enum=telemetry.Side" json:"side,omitempty"`
	FenceVersion  uint32                 `protobuf:"varint,10,opt,name=fence_version,json=fenceVersion,proto3" json:"fence_version,omitempty"`
	Battery       uint32                 `protobuf:"varint,11,opt,name=battery,proto3" json:"battery,omitempty"`
	Number        uint32                 `protobuf:"varint,12,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cow) Reset() {
	*x = Cow{}
	mi := &file_proto_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cow) ProtoMessage() {}

func (x *Cow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cow.ProtoReflect.Descriptor instead.
func (*Cow) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *Cow) GetCollarId() string {
	if x != nil {
		return x.CollarId
	}
	return ""
}

func (x *Cow) GetPaddockId() string {
	if x != nil {
		return x.PaddockId
	}
	return ""
}

func (x *Cow) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Cow) GetLatE6() int32 {
	if x != nil {
		return x.LatE6
	}
	return 0
}

func (x *Cow) GetLngE6() int32 {
	if x != nil {
		return x.LngE6
	}
	return 0
}

func (x *Cow) GetHeadingDeg() uint32 {
	if x != nil {
		return x.HeadingDeg
	}
	return 0
}

func (x *Cow) GetState() State {
	if x != nil {
		return x.State
	}
	return State_INSIDE
}

func (x *Cow) GetLevel() Cue {
	if x != nil {
		return x.Level
	}
	return Cue_CUE_NONE
}

func (x *Cow) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_NONE
}

func (x *Cow) GetFenceVersion() uint32 {
	if x != nil {
		return x.FenceVersion
	}
	return 0
}

func (x *Cow) GetBattery() uint32 {
	if x != nil {
		return x.Battery
	}
	return 0
}

func (x *Cow) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_proto_telemetry_proto protoreflect.FileDescriptor

const file_proto_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x15proto/telemetry.proto\x12\ttelemetry\"f\n" +
	"\n" +
	"FarmSecond\x12\x1b\n" +
	"\tfarmer_id\x18\x01 \x01(\tR\bfarmerId\x12\x17\n" +
	"\atime_ms\x18\x02 \x01(\x03R\x06timeMs\x12\"\n" +
	"\x04cows\x18\x03 \x03(\v2\x0e.telemetry.CowR\x04cows\"\xec\x02\n" +
	"\x03Cow\x12\x1b\n" +
	"\tcollar_id\x18\x01 \x01(\tR\bcollarId\x12\x1d\n" +
	"\n" +
	"paddock_id\x18\x02 \x01(\tR\tpaddockId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x15\n" +
	"\x06lat_e6\x18\x04 \x01(\x11R\x05latE6\x12\x15\n" +
	"\x06lng_e6\x18\x05 \x01(\x11R\x05lngE6\x12\x1f\n" +
	"\vheading_deg\x18\x06 \x01(\rR\n" +
	"headingDeg\x12&\n" +
	"\x05state\x18\a \x01(\x0e2\x10.telemetry.StateR\x05state\x12$\n" +
	"\x05level\x18\b \x01(\x0e2\x0e.telemetry.CueR\x05level\x12#\n" +
	"\x04side\x18\t \x01(\x0e2\x0f.telemetry.SideR\x04side\x12#\n" +
	"\rfence_version\x18\n" +
	" \x01(\rR\ffenceVersion\x12\x18\n" +
	"\abattery\x18\v \x01(\rR\abattery\x12\x16\n" +
	"\x06number\x18\f \x01(\rR\x06number*:\n" +
	"\x05State\x12\n" +
	"\n" +
	"\x06INSIDE\x10\x00\x12\v\n" +
	"\aWARNING\x10\x01\x12\f\n" +
	"\bBREACHED\x10\x02\x12\n" +
	"\n" +
	"\x06MOVING\x10\x03*8\n" +
	"\x03Cue\x12\f\n" +
	"\bCUE_NONE\x10\x00\x12\t\n" +
	"\x05AUDIO\x10\x01\x12\r\n" +
	"\tVIBRATION\x10\x02\x12\t\n" +
	"\x05PULSE\x10\x03*4\n" +
	"\x04Side\x12\r\n" +
	"\tSIDE_NONE\x10\x00\x12\b\n" +
	"\x04LEFT\x10\x01\x12\t\n" +
	"\x05RIGHT\x10\x02\x12\b\n" +
	"\x04BOTH\x10\x03B'Z%github.com/veerbal1/rancher/telemetryb\x06proto3"

var (
	file_proto_telemetry_proto_rawDescOnce sync.Once
	file_proto_telemetry_proto_rawDescData []byte
)

func file_proto_telemetry_proto_rawDescGZIP() []byte {
	file_proto_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)))
	})
	return file_proto_telemetry_proto_rawDescData
}

var file_proto_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_telemetry_proto_goTypes = []any{
	(State)(0),         // 0: telemetry.State
	(Cue)(0),           // 1: telemetry.Cue
	(Side)(0),          // 2: telemetry.Side
	(*FarmSecond)(nil), // 3: telemetry.FarmSecond
	(*Cow)(nil),        // 4: telemetry.Cow
}
var file_proto_telemetry_proto_depIdxs = []int32{
	4, // 0: telemetry.FarmSecond.cows:type_name -> telemetry.Cow
	0, // 1: telemetry.Cow.state:type_name -> telemetry.State
	1, // 2: telemetry.Cow.level:type_name -> telemetry.Cue
	2, // 3: telemetry.Cow.side:type_name -> telemetry.Side
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_telemetry_proto_init() }
func file_proto_telemetry_proto_init() {
	if File_proto_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_telemetry_proto_depIdxs,
		EnumInfos:         file_proto_telemetry_proto_enumTypes,
		MessageInfos:      file_proto_telemetry_proto_msgTypes,
	}.Build()
	File_proto_telemetry_proto = out.File
	file_proto_telemetry_proto_goTypes = nil
	file_proto_telemetry_proto_depIdxs = nil
}
